baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Kumaravel Rajan'
theme = 'PaperMod'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['&&', '&&']]
[params]
  math = true